spring.application.name=Proyectoweb


server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto
spring.datasource.username=root
spring.datasource.password=machomacho13

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
